
#
# This makefile was generated with the following command:
# /home/madoery/omnetpp-5.1/bin/opp_runall -j1 ../../../src/dtnsim case0.ini -n ../../../src -u Cmdenv -c dtnsim
#

SIMULATIONCMD = ../../../src/dtnsim case0.ini -n ../../../src -u Cmdenv -c dtnsim -s --cmdenv-redirect-output=true
TARGETS =  batch0

.PHONY: $(TARGETS)

all: $(TARGETS)
	@echo All runs completed.

batch0:
	$(SIMULATIONCMD) -r 0,1


